### ISSUE TITLE
Issues in countris

### ISSUE THREAD

**Issue by javadebadi** [javadebadi/hep-analysis#8]
Some countries are not present in the create CSV file from web scraping such as Korea and Iran

**Comment by javadebadi** [comment]
Hi Vahid,
I found a problem in countries' data. Would you please find out what is the problem? @VahidHosseinzadeh

**Comment by VahidHosseinzadeh** [comment]
Hi Javad. I do not know what is the problem. I will work on it. But other problem is these two tables have countries and also some areas (not country specifically). We have 195 countries in the world (Google says) So, is it enough to just have them? I do not know but maybe there are some better references.

**Comment by VahidHosseinzadeh** [comment]
Ok, I found what is the problem. I merged the two tables on countries and also on iso3. But in one of the tables it was for example Iran and the other Iran (Islamic rep.....) so it push this out. Now I joined them only on the iso3 which is sufficient.

**Comment by javadebadi** [comment]
Hi @VahidHosseinzadeh , 
Thank you for solving the issue. 
I didn't understand the second problem you were talking about. Could you please explain more and maybe give us an example of what is the problem?

**Comment by VahidHosseinzadeh** [comment]
Hi Javad, Thanks. 
I meant that now we have some countries in our tables that are not really countries. They are some areas! For example look at this : Antarctica. it has 0 population! This is not really a problem per se. But in future if we want to average sth on real countries we should be careful.

**Comment by javadebadi** [comment]
Ok, Vahid. I see. As you said for now it is not a problem. 
Since the issue is solved, I close the issue. Thank you @VahidHosseinzadeh .
